version: '3'

services:
  ch_server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    volumes:
      - dataclickhouse:/var/lib/clickhouse
      - ./data-import/pp-complete.csv:/var/data-import/pp-complete.csv
    networks:
        - ch_ntw

  ch_client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
    networks:
        - ch_ntw

networks:
  ch_ntw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.222.1.0/24

volumes:
  dataclickhouse:
    driver_opts:
      device: ./data/
      o: bind
      type: none
